apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      name: pod-api
      labels:
        app: api
    spec:
      containers:
        - name: api-container
          image: andssil/techchallenge:latest
          ports:
            - containerPort: 8081
          env:  
            - name: ASPNETCORE_ENVIRONMENT
              value: Production           
          imagePullPolicy: IfNotPresent               
          resources:
            requests:
              cpu: 50m  